<?php

return [
    'adminEmail' => 'admin@example.com',

    'languages' => [
        'ru' => 'Русский',
        //'en' => 'English',
    ],
    'commandsLabels' => [
        'ru' => [
            '/settings' => 'Опции',
            '/measurement' => 'Измерения',
            '/city' => 'Город',
            '/language' => 'Язык',
            '/notification' => 'Уведомления',
            '/today' => 'На сегодня',
            '/tomorrow' => 'На завтра',
            '/5days' => 'На 5 дней',
            '/usd' => 'USD',
            '/eur' => 'EUR',
            '/rub' => 'RUB',
            '/start' => 'На главную',
            '/currencyauction' => 'Валютный аукцион',
            '/mb' => 'Межбанк',
            '/cards' => 'Visa/MasterCard',
            '/bankcourses' => 'Курс в банках',
        ],
        'en' => [
            '/settings' => 'settings',
            '/measurement' => 'units',
            '/city' => 'city',
            '/language' => 'language',
            '/notification' => 'notification',
            '/today' => 'for today',
            '/tomorrow' => 'for tomorrow',
            '/5days' => 'for 5 days',
            '/usd' => 'USD',
            '/eur' => 'EUR',
            '/rub' => 'RUB',
            '/start' => 'main menu',
        ],
    ],
    'units' => [
        'C' => 'metric',
        'F' => 'imperial'
    ],
    'emoji' => [
        'weather' => [
            '01d' => "\u2600",
            '02d' => "\u26C5",
            '03d' => "\u2601",
            '04d' => "\u2601",
            '09d' => "\u2614",
            '10d' => "\u2614",
            '11d' => "\u26A1",
            '13d' => "\u2744",
            '50d' => "\uD83C\uDF01",
            '01n' => "\uD83C\uDF19",
            '02n' => "\u26C5",
            '03n' => "\u2601",
            '04n' => "\u2601",
            '09n' => "\u2614",
            '10n' => "\u2614",
            '11n' => "\u26A1",
            '13n' => "\u2744",
            '50n' => "\uD83C\uDF01",
        ],
        'menu' => [
            'location' => "\uD83D\uDCCD",
            'units' => "\uD83D\uDD27",
            'language' => "\uD83C\uDF0F",
            'back' => "\u2B05"
        ]
    ],
    'cities' => [
        'kiev' => 'Киев',
        'berdjansk' => 'Бердянск',
        'vinnitsa' => 'Винница',
        'dnepropetrovsk' => 'Днепропетровск',
        'donetsk' => 'Донецк',
        'zhitomir' => 'Житомир',
        'zaporozhye' => 'Запорожье',
        'ivano-frankovsk' => 'Иванофранковск',
        'kievobl' => 'Киевская область',
        'kirovograd' => 'Кировоград',
        'kremenchug' => 'Кременчуг',
        'krivoyrog' => 'Кривой-рог',
        'lugansk' => 'Луганск',
        'lutsk' => 'Луцк',
        'lvov' => 'Львов',
        'mariupol' => 'Мариуполь',
        'melitopol' => 'Мелитополь',
        'nikolaev' => 'Николаев',
        'odessa' => 'Одесса',
        'pavlograd' => 'Павлоград',
        'poltava' => 'Полтава',
        'rovno' => 'Ровно',
        'sumy' => 'Сумы',
        'ternopol' => 'Тернополь',
        'uzhgorod' => 'Ужгород',
        'kharkov' => 'Харьков',
        'kherson' => 'Херсон',
        'khmelnitskiy' => 'Хмельницкий',
        'cherkassy' => 'Черкасы',
        'chernigov' => 'Чернигов',
        'chernovtsy' => 'Черновци',
    ],
];
