<?php

return [
    'adminEmail' => 'admin@example.com',
    'languages' => [
        'ru' => 'Русский',
    ],
    'commandsLabels' => [
        'ru' => [
            '/settings' => 'Опции',
            '/measurement' => 'Измерения',
            '/city' => 'Город',
            '/language' => 'Язык',
            '/today' => 'На сегодня',
            '/tomorrow' => 'На завтра',
            '/5days' => 'На 5 дней',
            '/start' => 'На главную',
            '/currencyauction' => 'Валютный аукцион',
            '/mb' => 'Межбанк',
            '/cards' => 'Visa/MasterCard',
            '/bankcourses' => 'Курс в банках',
            '/notifications' => 'Уведомления',
            '/setusdnotification' => 'Для В.А. USD',
            '/seteurnotification' => 'Для В.А. EUR',
            '/setrubnotification' => 'Для В.А. RUB',
            '/setmbnotification' => 'Для Межбанка',
            '/setcardsnotification' => "Для Карт",
            '/setbankscoursenotification' => 'Для Курсов в Банках',
            '/usd' => 'USD',
            '/eur' => 'EUR',
            '/rub' => 'RUB',
        ],
        'en' => [
            '/settings' => 'settings',
            '/measurement' => 'units',
            '/city' => 'city',
            '/language' => 'language',
            '/today' => 'for today',
            '/tomorrow' => 'for tomorrow',
            '/5days' => 'for 5 days',
            '/usd' => 'USD',
            '/eur' => 'EUR',
            '/rub' => 'RUB',
            '/start' => 'main menu',
            '/notifications' => 'Notifications',
            '/setusdnotification' => 'Notifications C.A. USD',
            '/seteurnotification' => 'Notifications C.A. EUR',
            '/setrubnotification' => 'Notifications C.A. RUB',
        ],
    ],
    'emoji' => [
        'menu' => [
            'location' => "\uD83D\uDCCD",
            'units' => "\uD83D\uDD27",
            'language' => "\uD83C\uDF0F",
            'back' => "\u2B05"
        ]
    ],
    'cities' => [
        'kiev' => 'Киев',
        'berdjansk' => 'Бердянск',
        'vinnitsa' => 'Винница',
        'dnepropetrovsk' => 'Днепропетровск',
        'donetsk' => 'Донецк',
        'zhitomir' => 'Житомир',
        'zaporozhye' => 'Запорожье',
        'ivano-frankovsk' => 'Иванофранковск',
        'kievobl' => 'Киевская область',
        'kirovograd' => 'Кировоград',
        'kremenchug' => 'Кременчуг',
        'krivoyrog' => 'Кривой-рог',
        'lugansk' => 'Луганск',
        'lutsk' => 'Луцк',
        'lvov' => 'Львов',
        'mariupol' => 'Мариуполь',
        'melitopol' => 'Мелитополь',
        'nikolaev' => 'Николаев',
        'odessa' => 'Одесса',
        'pavlograd' => 'Павлоград',
        'poltava' => 'Полтава',
        'rovno' => 'Ровно',
        'sumy' => 'Сумы',
        'ternopol' => 'Тернополь',
        'uzhgorod' => 'Ужгород',
        'kharkov' => 'Харьков',
        'kherson' => 'Херсон',
        'khmelnitskiy' => 'Хмельницкий',
        'cherkassy' => 'Черкасы',
        'chernigov' => 'Чернигов',
        'chernovtsy' => 'Черновци',
    ],
];
