<?php

return [
    'adminEmail' => 'admin@example.com',
    'languages' => [
        'ru' => 'Русский',
        'en' => 'English',
    ],
    'commandsLabels' => [
        'ru' => [
            '/settings' => 'опции',
            '/measurement' => 'измерения',
            '/city' => 'город',
            '/language' => 'язык',
            '/notification' => 'уведомления',
            '/today' => 'на сегодня',
            '/tomorrow' => 'на завтра',
            '/5days' => 'на 5 дней',
            '/usd' => 'USD',
            '/eur' => 'EUR',
            '/rub' => 'RUB',
        ],
        'en' => [
            '/settings' => 'settings',
            '/measurement' => 'units',
            '/city' => 'city',
            '/language' => 'language',
            '/notification' => 'notification',
            '/today' => 'for today',
            '/tomorrow' => 'for tomorrow',
            '/5days' => 'for 5 days',
            '/usd' => 'USD',
            '/eur' => 'EUR',
            '/rub' => 'RUB',
        ],
    ],
    'units' => [
        'C' => 'metric',
        'F' => 'imperial'
    ],
    'emoji' => [
        'weather' => [
            '01d' => "\u2600",
            '02d' => "\u26C5",
            '03d' => "\u2601",
            '04d' => "\u2601",
            '09d' => "\u2614",
            '10d' => "\u2614",
            '11d' => "\u26A1",
            '13d' => "\u2744",
            '50d' => "\uD83C\uDF01",
            '01n' => "\uD83C\uDF19",
            '02n' => "\u26C5",
            '03n' => "\u2601",
            '04n' => "\u2601",
            '09n' => "\u2614",
            '10n' => "\u2614",
            '11n' => "\u26A1",
            '13n' => "\u2744",
            '50n' => "\uD83C\uDF01",
        ],
        'menu' => [
            'location' => "\uD83D\uDCCD",
            'units' => "\uD83D\uDD27",
            'language' => "\uD83C\uDF0F",
            'back' => "\u2B05"
        ]
    ],
    'cities' => [
        'kiev' => 'киев',
        'berdjansk' => 'бердянск',
        'vinnitsa' => 'винница',
        'dnepropetrovsk' => 'днепропетровск',
        'donetsk' => 'донецк',
        'zhitomir' => 'житомир',
        'zaporozhye' => 'запорожье',
        'ivano-frankovsk' => 'иванофранковск',
        'kievobl' => 'киевская область',
        'kirovograd' => 'кировоград',
        'kremenchug' => 'кременчуг',
        'krivoyrog' => 'кривой-рог',
        'lugansk' => 'луганск',
        'lutsk' => 'луцк',
        'lvov' => 'львов',
        'mariupol' => 'мариуполь',
        'melitopol' => 'мелитополь',
        'nikolaev' => 'николаев',
        'odessa' => 'одесса',
        'pavlograd' => 'павлоград',
        'poltava' => 'полтава',
        'rovno' => 'ровно',
        'sumy' => 'сумы',
        'ternopol' => 'тернополь',
        'uzhgorod' => 'ужгород',
        'kharkov' => 'харьков',
        'kherson' => 'херсон',
        'khmelnitskiy' => 'хмельницкий',
        'cherkassy' => 'черкасы',
        'chernigov' => 'чернигов',
        'chernovtsy' => 'черновци',
    ]
];
